# Generated by Django 3.1.2 on 2020-11-05 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0006_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='post',
            name='dt_publicacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Dt Publicacao'),
            preserve_default=False,
        ),
    ]
