# Generated by Django 3.1.2 on 2020-11-05 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0007_auto_20201104_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_post', models.CharField(max_length=50)),
                ('txt_post', models.CharField(max_length=500)),
                ('dt_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Publicacao')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.perfil')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
